name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow
        pip install -r requirements.txt

    - name: Deploy DAGs
      run: |
        export AIRFLOW_HOME=$(pwd)/airflow
        airflow db init
        mv model_monitoring_dag.py $AIRFLOW_HOME/dags
        airflow webserver -p 8080 -D &
        airflow scheduler


