name: Flask CI

on:
  push:
    branches:
      - main  # adjust this branch name based on your repository's default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    
    - name: Expose Flask application with ngrok
      run: |
        export FLASK_APP=flask_app.py
        python -m flask run --host=127.0.0.1 --port=5000 &
        ngrok http 5000 -log=stdout > ngrok.log &
        sleep 5  # Allow ngrok to initialize


    

    
