name: Run Airflow DAG

on:
  push:
    branches:
      - main

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create DAGs directory
      run: mkdir -p $GITHUB_WORKSPACE/dags/

    - name: Copy specific files to DAGs folder
      run: |
        cp Naive_bayes.pkl imp_scale prima_13.csv test_file.csv winsor model_drift_dag.py  $GITHUB_WORKSPACE/dags/
      
    - name: Install dependencies
      run: |
        pip install apache-airflow
        pip install pandas scikit-learn evidently feature_engine

    - name: Set up Airflow
      run: |
        export AIRFLOW_HOME=$(pwd)
        

    - name: Airflow db
      run: |
        cd $AIRFLOW_HOME
        airflow db init
        echo "[core]" >> airflow.cfg
        echo "dags_folder = $AIRFLOW_HOME/dags" >> airflow.cfg
        echo "load_examples = False" >> airflow.cfg

    - name: Run Airflow scheduler
      run: |
        cd $AIRFLOW_HOME
        airflow scheduler --daemon

    - name: Wait for scheduler to start
      run: sleep 10

    - name: Run Airflow DAG
      run: |
        cd $AIRFLOW_HOME
        airflow tasks test conditional_model_drift_detection_dag detect_model_drift_task 2023-01-01


    - name: Tear down Airflow
      run: |
        pkill -f "airflow scheduler"






